import { ApiProperty } from '@nestjs/swagger';

export class RevenueByMonthDto {
  @ApiProperty({ description: 'Month label in YYYY-MM format', example: '2024-01' })
  month: string;

  @ApiProperty({ description: 'Total revenue amount for this month', example: 15000000 })
  amount: number;
}

export class StudentGrowthDto {
  @ApiProperty({ description: 'Month label in YYYY-MM format', example: '2024-01' })
  month: string;

  @ApiProperty({ description: 'Number of active students in this month', example: 312 })
  count: number;
}

export class TopCourseDto {
  @ApiProperty({ description: 'Course unique ID', format: 'uuid' })
  courseId: string;

  @ApiProperty({ description: 'Course name', example: 'English for Beginners' })
  name: string;

  @ApiProperty({ description: 'Total number of enrolled students', example: 87 })
  enrollmentCount: number;

  @ApiProperty({ description: 'Revenue generated by this course', example: 12000000 })
  revenue: number;
}

export class BranchComparisonDto {
  @ApiProperty({ description: 'Branch name', example: 'Tashkent Branch' })
  branchName: string;

  @ApiProperty({ description: 'Number of students in this branch', example: 120 })
  students: number;

  @ApiProperty({ description: 'Total revenue from this branch', example: 15000000 })
  revenue: number;

  @ApiProperty({ description: 'Average attendance rate in percent', example: 88.2 })
  attendanceRate: number;
}

export class UserGrowthPointDto {
  @ApiProperty({ description: 'Month label in YYYY-MM format', example: '2024-03' })
  month: string;

  @ApiProperty({ description: 'Total active students this month', example: 312 })
  students: number;

  @ApiProperty({ description: 'Total active teachers this month', example: 22 })
  teachers: number;
}

export class GlobalAnalyticsDto {
  @ApiProperty({ description: 'Total platform revenue', example: 120000000 })
  totalRevenue: number;

  @ApiProperty({ description: 'Total students across all branches', example: 342 })
  totalStudents: number;

  @ApiProperty({ description: 'Total teachers across all branches', example: 24 })
  totalTeachers: number;

  @ApiProperty({ description: 'Total number of courses', example: 18 })
  totalCourses: number;

  @ApiProperty({ description: 'Total active groups', example: 15 })
  activeGroups: number;

  @ApiProperty({ description: 'Platform-wide average attendance rate in percent', example: 87.5 })
  attendanceRate: number;

  @ApiProperty({
    description: 'Revenue breakdown by month',
    type: [RevenueByMonthDto],
  })
  revenueByMonth: RevenueByMonthDto[];

  @ApiProperty({
    description: 'Student count growth by month',
    type: [StudentGrowthDto],
  })
  studentGrowth: StudentGrowthDto[];

  @ApiProperty({
    description: 'Top courses by enrollment and revenue',
    type: [TopCourseDto],
  })
  topCourses: TopCourseDto[];

  @ApiProperty({
    description: 'Revenue and performance comparison between branches',
    type: [BranchComparisonDto],
  })
  branchComparison: BranchComparisonDto[];

  @ApiProperty({
    description: 'User growth trend — last 12 months',
    type: [UserGrowthPointDto],
  })
  userGrowth: UserGrowthPointDto[];
}
